-- ============================================================
-- Football Staging Layer (Silver)
-- ============================================================

CREATE TABLE IF NOT EXISTS SPORT_ANALYTICS.STAGING.FOOTBALL_FIXTURES AS
SELECT * FROM SPORT_ANALYTICS.RAW.FOOTBALL_FIXTURES WHERE 1=0;

MERGE INTO SPORT_ANALYTICS.STAGING.FOOTBALL_FIXTURES AS tgt
USING (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY FIXTURE_ID ORDER BY _LOADED_AT DESC) AS rn
    FROM SPORT_ANALYTICS.RAW.FOOTBALL_FIXTURES
) AS src
ON tgt.FIXTURE_ID = src.FIXTURE_ID
WHEN MATCHED AND src.rn = 1 THEN
    UPDATE SET
        tgt.STATUS       = src.STATUS,
        tgt.STATUS_SHORT = src.STATUS_SHORT,
        tgt.HOME_GOALS   = src.HOME_GOALS,
        tgt.AWAY_GOALS   = src.AWAY_GOALS,
        tgt._LOADED_AT   = src._LOADED_AT
WHEN NOT MATCHED AND src.rn = 1 THEN
    INSERT SELECT * EXCLUDE (rn) FROM src;

-- Standings (full refresh — always current snapshot)
CREATE OR REPLACE TABLE SPORT_ANALYTICS.STAGING.FOOTBALL_STANDINGS AS
SELECT *
FROM SPORT_ANALYTICS.RAW.FOOTBALL_STANDINGS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY LEAGUE_ID, SEASON, TEAM_ID ORDER BY _LOADED_AT DESC
) = 1;
